<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>GetUser_TDD_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ed550129-f401-4012-9a09-7285c044a2ae</testSuiteGuid>
   <testCaseLink>
      <guid>e9c994f5-4501-48c4-971b-e0cc18795205</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>2</defaultValue>
         <description></description>
         <id>03cce7f5-f20a-4886-8bf8-32191275b8a9</id>
         <masked>false</masked>
         <name>EndId_TC</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/ReqRes_TDD/GetUser_TDD_TC</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>03cce7f5-f20a-4886-8bf8-32191275b8a9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
